### ISSUE TITLE
userId and tokenId are hard coded

### ISSUE THREAD

**Issue by ComeBurguburu** [tjayantha/rancher_ansible#1]
Why userId and tokenId are hard coded ?
Can't we extract them from restdata here : https://github.com/tjayantha/rancher_ansible/blob/8f980b055662214f5cbea556ea428771123ef170/roles/rancher/tasks/rancher_server.yml#L43 ?

```yaml
- name: set rancher token
      set_fact:
        userId: "{{ restdata.json['token'].split(':')[0] }}"
        tokenId: "{{ restdata.json['token'] }}"
        tokenPass: "{{restdata.json['token'].split(':')[1]}}"
````
